services:
  open-box:
    restart: unless-stopped
    volumes:
      - 'open-box-data:/opt/openlist/data'
    ports:
      - '5244:5244'
      - '5245:5245'
    environment:
      UMASK: "022"
      TZ: Asia/Manila
      DB_TYPE: ${DB_TYPE:-sqlite3}
      DB_HOST: ${DB_HOST:-}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-}
      DB_PASSWORD: ${DB_PASSWORD:-}
      DB_NAME: ${DB_NAME:-open-box}
      DB_SSL_MODE: ${DB_SSL_MODE:-require}
    container_name: open-box
    image: 'huxleysee/open-box:latest'

volumes:
  open-box-data:
