services:
  open-box:
    restart: unless-stopped
    volumes:
      - 'open-box-data:/opt/openlist/data'
    ports:
      - '5244:5244'
      - '5245:5245'
    environment:
      UMASK: "022"
      TZ: Asia/Manila
      DB_TYPE: postgres
      DB_DSN: ${DB_DSN:?DB_DSN must target open-platform with search_path=open_box}
      DB_TABLE_PREFIX: x_
    container_name: open-box
    image: 'hillstreet/open-box@sha256:3dec2e8a5c081fc19a7e28d1fba8416e126cd6ef4f027710d5178d23c0f6d06a'

volumes:
  open-box-data:
